apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao-sistema-statefulset
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 31822
  selector:
    name: aplicacao-sistema-pod-statefulset
